name: money_expense
description: Aplikasi untuk mencatat pengeluaran harian

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.4.0
  flutter_staggered_animations: "^0.1.2"
  flutter_svg: ^0.19.0
  fluttertoast: ^7.1.1
  google_fonts: ^1.1.0
  grouped_list: ^3.4.0
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  intl: ^0.16.1
  provider: ^4.3.2+2

dev_dependencies:
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
